/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.models.OrgKubeflowV1TFJobSpecTfReplicaSpecs;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OrgKubeflowV1TFJobSpec
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-31T03:01:37.074Z")
public class OrgKubeflowV1TFJobSpec {
  @SerializedName("tfReplicaSpecs")
  private OrgKubeflowV1TFJobSpecTfReplicaSpecs tfReplicaSpecs = null;

  public OrgKubeflowV1TFJobSpec tfReplicaSpecs(OrgKubeflowV1TFJobSpecTfReplicaSpecs tfReplicaSpecs) {
    this.tfReplicaSpecs = tfReplicaSpecs;
    return this;
  }

   /**
   * Get tfReplicaSpecs
   * @return tfReplicaSpecs
  **/
  @ApiModelProperty(value = "")
  public OrgKubeflowV1TFJobSpecTfReplicaSpecs getTfReplicaSpecs() {
    return tfReplicaSpecs;
  }

  public void setTfReplicaSpecs(OrgKubeflowV1TFJobSpecTfReplicaSpecs tfReplicaSpecs) {
    this.tfReplicaSpecs = tfReplicaSpecs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgKubeflowV1TFJobSpec orgKubeflowV1TFJobSpec = (OrgKubeflowV1TFJobSpec) o;
    return Objects.equals(this.tfReplicaSpecs, orgKubeflowV1TFJobSpec.tfReplicaSpecs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tfReplicaSpecs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgKubeflowV1TFJobSpec {\n");
    
    sb.append("    tfReplicaSpecs: ").append(toIndentedString(tfReplicaSpecs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

