/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.kubernetes.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * OrgKubeflowV1TFJobSpecTfReplicaSpecs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-31T03:01:37.074Z")
public class OrgKubeflowV1TFJobSpecTfReplicaSpecs {
  @SerializedName("Chief")
  // As SnakeYAML requires that member variable name must be the same as
  // the attribute of yaml, so the attribute in yaml can't be chief.
  private OrgKubeflowV1TFJobSpecTfReplicaSpecsChief chief = null;

  @SerializedName("PS")
  private OrgKubeflowV1TFJobSpecTfReplicaSpecsPS PS = null;

  @SerializedName("Worker")
  // As SnakeYAML requires that member variable name must be the same as
  // the attribute of yaml, so the attribute in yaml can't be Worker.
  private OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker worker = null;

  public OrgKubeflowV1TFJobSpecTfReplicaSpecs chief(OrgKubeflowV1TFJobSpecTfReplicaSpecsChief chief) {
    this.chief = chief;
    return this;
  }

   /**
   * Get chief
   * @return chief
  **/
  @ApiModelProperty(value = "")
  public OrgKubeflowV1TFJobSpecTfReplicaSpecsChief getChief() {
    return chief;
  }

  public void setChief(OrgKubeflowV1TFJobSpecTfReplicaSpecsChief chief) {
    this.chief = chief;
  }

  public OrgKubeflowV1TFJobSpecTfReplicaSpecs PS(OrgKubeflowV1TFJobSpecTfReplicaSpecsPS PS) {
    this.PS = PS;
    return this;
  }

   /**
   * Get PS
   * @return PS
  **/
  @ApiModelProperty(value = "")
  public OrgKubeflowV1TFJobSpecTfReplicaSpecsPS getPS() {
    return PS;
  }

  public void setPS(OrgKubeflowV1TFJobSpecTfReplicaSpecsPS PS) {
    this.PS = PS;
  }

  public OrgKubeflowV1TFJobSpecTfReplicaSpecs worker(OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker worker) {
    this.worker = worker;
    return this;
  }

   /**
   * Get worker
   * @return worker
  **/
  @ApiModelProperty(value = "")
  public OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker getWorker() {
    return worker;
  }

  public void setWorker(OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker worker) {
    this.worker = worker;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgKubeflowV1TFJobSpecTfReplicaSpecs orgKubeflowV1TFJobSpecTfReplicaSpecs = (OrgKubeflowV1TFJobSpecTfReplicaSpecs) o;
    return Objects.equals(this.chief, orgKubeflowV1TFJobSpecTfReplicaSpecs.chief) &&
        Objects.equals(this.PS, orgKubeflowV1TFJobSpecTfReplicaSpecs.PS) &&
        Objects.equals(this.worker, orgKubeflowV1TFJobSpecTfReplicaSpecs.worker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chief, PS, worker);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgKubeflowV1TFJobSpecTfReplicaSpecs {\n");
    
    sb.append("    chief: ").append(toIndentedString(chief)).append("\n");
    sb.append("    PS: ").append(toIndentedString(PS)).append("\n");
    sb.append("    worker: ").append(toIndentedString(worker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

