/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.kubernetes.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-31T03:01:37.074Z")
public class OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker {
  @SerializedName("replicas")
  private Integer replicas = null;

  @SerializedName("template")
  private V1PodTemplateSpec template = null;

  public OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker replicas(Integer replicas) {
    this.replicas = replicas;
    return this;
  }

  public OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker template(V1PodTemplateSpec template) {
    this.template = template;
    return this;
  }

   /**
   * Get replicas
   * minimum: 1
   * @return replicas
  **/
  @ApiModelProperty(value = "")
  public Integer getReplicas() {
    return replicas;
  }

  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }

  /**
   * Template is the object that describes the pod that will be created for this TFReplicaSpecsWorker
   * @return template
   **/
  @ApiModelProperty(value = "Template is the object that describes the pod that will be created for this TFReplicaSpecsWorker")
  public V1PodTemplateSpec getTemplate() {
    return template;
  }

  public void setTemplate(V1PodTemplateSpec template) {
    this.template = template;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker orgKubeflowV1TFJobSpecTfReplicaSpecsWorker = (OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker) o;
    return Objects.equals(this.replicas, orgKubeflowV1TFJobSpecTfReplicaSpecsWorker.replicas)
        && Objects.equals(this.template, orgKubeflowV1TFJobSpecTfReplicaSpecsWorker.template);
  }

  @Override
  public int hashCode() {
    return Objects.hash(replicas, template);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgKubeflowV1TFJobSpecTfReplicaSpecsWorker {\n");

    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

